# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import zace_tank_battle_pb2 as zace__tank__battle__pb2


class TankBattleServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetMapGrid = channel.unary_unary(
                '/zace_tank_battle.TankBattleService/GetMapGrid',
                request_serializer=zace__tank__battle__pb2.Empty.SerializeToString,
                response_deserializer=zace__tank__battle__pb2.MapGrid.FromString,
                )
        self.JoinGame = channel.unary_stream(
                '/zace_tank_battle.TankBattleService/JoinGame',
                request_serializer=zace__tank__battle__pb2.PlayerJoinRequest.SerializeToString,
                response_deserializer=zace__tank__battle__pb2.GameState.FromString,
                )
        self.SendAction = channel.unary_unary(
                '/zace_tank_battle.TankBattleService/SendAction',
                request_serializer=zace__tank__battle__pb2.PlayerAction.SerializeToString,
                response_deserializer=zace__tank__battle__pb2.Empty.FromString,
                )


class TankBattleServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetMapGrid(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def JoinGame(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendAction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TankBattleServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetMapGrid': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMapGrid,
                    request_deserializer=zace__tank__battle__pb2.Empty.FromString,
                    response_serializer=zace__tank__battle__pb2.MapGrid.SerializeToString,
            ),
            'JoinGame': grpc.unary_stream_rpc_method_handler(
                    servicer.JoinGame,
                    request_deserializer=zace__tank__battle__pb2.PlayerJoinRequest.FromString,
                    response_serializer=zace__tank__battle__pb2.GameState.SerializeToString,
            ),
            'SendAction': grpc.unary_unary_rpc_method_handler(
                    servicer.SendAction,
                    request_deserializer=zace__tank__battle__pb2.PlayerAction.FromString,
                    response_serializer=zace__tank__battle__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'zace_tank_battle.TankBattleService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TankBattleService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetMapGrid(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/zace_tank_battle.TankBattleService/GetMapGrid',
            zace__tank__battle__pb2.Empty.SerializeToString,
            zace__tank__battle__pb2.MapGrid.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def JoinGame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/zace_tank_battle.TankBattleService/JoinGame',
            zace__tank__battle__pb2.PlayerJoinRequest.SerializeToString,
            zace__tank__battle__pb2.GameState.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendAction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/zace_tank_battle.TankBattleService/SendAction',
            zace__tank__battle__pb2.PlayerAction.SerializeToString,
            zace__tank__battle__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
