# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zace_tank_battle.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16zace_tank_battle.proto\x12\x10zace_tank_battle\"\x1d\n\x05Point\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\"u\n\x04Tank\x12\n\n\x02id\x18\x01 \x01(\t\x12)\n\x08position\x18\x02 \x01(\x0b\x32\x17.zace_tank_battle.Point\x12\x13\n\x0bplayer_name\x18\x03 \x01(\t\x12\x0e\n\x06health\x18\x04 \x01(\x05\x12\x11\n\tdirection\x18\x05 \x01(\t\"X\n\x06\x42ullet\x12)\n\x08position\x18\x01 \x01(\x0b\x32\x17.zace_tank_battle.Point\x12\x11\n\tdirection\x18\x02 \x01(\t\x12\x10\n\x08owner_id\x18\x03 \x01(\t\"\xed\x01\n\tGameState\x12%\n\x05tanks\x18\x01 \x03(\x0b\x32\x16.zace_tank_battle.Tank\x12)\n\x07\x62ullets\x18\x02 \x03(\x0b\x32\x18.zace_tank_battle.Bullet\x12&\n\x05walls\x18\x03 \x03(\x0b\x32\x17.zace_tank_battle.Point\x12\x37\n\x06scores\x18\x04 \x03(\x0b\x32\'.zace_tank_battle.GameState.ScoresEntry\x1a-\n\x0bScoresEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\"~\n\x0cPlayerAction\x12\x11\n\tplayer_id\x18\x01 \x01(\t\x12\x13\n\x0b\x61\x63tion_type\x18\x02 \x01(\t\x12\x16\n\tdirection\x18\x03 \x01(\tH\x00\x88\x01\x01\x12\x14\n\x07message\x18\x04 \x01(\tH\x01\x88\x01\x01\x42\x0c\n\n_directionB\n\n\x08_message\".\n\x07MapGrid\x12#\n\x04rows\x18\x01 \x03(\x0b\x32\x15.zace_tank_battle.Row\"\x14\n\x03Row\x12\r\n\x05\x63\x65lls\x18\x01 \x03(\t\"(\n\x11PlayerJoinRequest\x12\x13\n\x0bplayer_name\x18\x01 \x01(\t\"\x07\n\x05\x45mpty2\xf2\x01\n\x11TankBattleService\x12\x42\n\nGetMapGrid\x12\x17.zace_tank_battle.Empty\x1a\x19.zace_tank_battle.MapGrid\"\x00\x12P\n\x08JoinGame\x12#.zace_tank_battle.PlayerJoinRequest\x1a\x1b.zace_tank_battle.GameState\"\x00\x30\x01\x12G\n\nSendAction\x12\x1e.zace_tank_battle.PlayerAction\x1a\x17.zace_tank_battle.Empty\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'zace_tank_battle_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_GAMESTATE_SCORESENTRY']._options = None
  _globals['_GAMESTATE_SCORESENTRY']._serialized_options = b'8\001'
  _globals['_POINT']._serialized_start=44
  _globals['_POINT']._serialized_end=73
  _globals['_TANK']._serialized_start=75
  _globals['_TANK']._serialized_end=192
  _globals['_BULLET']._serialized_start=194
  _globals['_BULLET']._serialized_end=282
  _globals['_GAMESTATE']._serialized_start=285
  _globals['_GAMESTATE']._serialized_end=522
  _globals['_GAMESTATE_SCORESENTRY']._serialized_start=477
  _globals['_GAMESTATE_SCORESENTRY']._serialized_end=522
  _globals['_PLAYERACTION']._serialized_start=524
  _globals['_PLAYERACTION']._serialized_end=650
  _globals['_MAPGRID']._serialized_start=652
  _globals['_MAPGRID']._serialized_end=698
  _globals['_ROW']._serialized_start=700
  _globals['_ROW']._serialized_end=720
  _globals['_PLAYERJOINREQUEST']._serialized_start=722
  _globals['_PLAYERJOINREQUEST']._serialized_end=762
  _globals['_EMPTY']._serialized_start=764
  _globals['_EMPTY']._serialized_end=771
  _globals['_TANKBATTLESERVICE']._serialized_start=774
  _globals['_TANKBATTLESERVICE']._serialized_end=1016
# @@protoc_insertion_point(module_scope)
